INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Иван', 'Иванов', '1975.06.25', 'Россия', 'Санкт Петербург');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Александр', 'Петров', '1955.06.27', 'Белоруссия', 'Минск');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Петр', 'Сидоров', '1991.01.03', 'Белоруссия', 'Гродно');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Валерий', 'Афанасьев ', '1995.04.01', 'Россия', 'Москва');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Юрий', 'Кузнецов', '1986.09.13', 'Белоруссия', 'Гомель');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Игорь', 'Попов', '1981.12.15', 'Россия', 'Москва');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Даниил', 'Соколов', '1968.10.21', 'Белоруссия', 'Брест');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Виталий', 'Васильев', '1988.08.11', 'Россия', 'Санкт Петербург');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Анатолий', 'Михайлов', '1993.03.12', 'Белоруссия', 'Брест');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Валерий', 'Новиков', '1978.10.20', 'Белоруссия', 'Витебск');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Илья', 'Федоров	', '1974.11.29', 'Белоруссия', 'Минск');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Александр', 'Морозов', '1969.05.14', 'Россия', 'Москва');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Денис', 'Гришин', '1996.09.13', 'Белоруссия', 'Гродно');
INSERT INTO `auto_service_db`.`consumer` (`firstName`, `lastName`, `birthDate`, `country`, `city`) VALUES ('Фёдор', 'Шаров', '1981.02.22', 'Россия', 'Санкт Петербург');

INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Kia', 'Sportage', '2014', 'black', '2.0 petrol', '53548', '6');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Suzuki', 'Vitara', '2015', 'orange', '1.6 petrol', '26329', '7');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Audi', 'A7', '2011', 'black', '3.0 diesel', '155743', '13');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Mitsubishi', 'Outlander', '2010', 'white', '2.0 petrol', '104752', '3');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Kia', 'Sorento', '2010', 'silver', '2.2 diesel', '140521', '5');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Toyota', 'Highlander', '2014', 'gray', '3.5 petrol', '88952', '5');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Land Rover', 'Evoque', '2012', 'black', '2.2 diesel', '76656', '10');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('BMW', 'X5', '2010', 'white', '4.8 petrol', '144521', '11');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Dodge', 'Ram', '2013', 'white', '5.7 petrol', '124565', '1');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Toyota', 'RAV4', '2015', 'gray', '2.0 petrol', '781914', '7');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('BMW', '740', '2013', 'red', '3.0 diesel', '102465', '14');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('BMW', 'X3', '2011', 'silver', '3.0 diesel', '120587', '6');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Volkswagen', 'Tiguan', '2014', 'white', '2.0 diesel', '86384', '14');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Volkswagen', 'Passat', '2011', 'gray', '2.0 diesel', '131251', '6');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Hyundai', 'Genesis', '2012', 'white', '2.0 petrol', '36002', '1');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Audi', 'A4', '2013', 'blue', '1.8 diesel', '129650', '7');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Mercedes', 'CL500', '2011', 'black', '4.7 diesel', '78905', '2');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Jeep', 'Wrangler', '2010', 'brown', '3.8 diesel', '55020', '9');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Jaguar', 'XJ', '2013', 'silver', '3.0 diesel', '62014', '5');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Skoda', 'Yeti', '2012', 'green', '1.4 petrol', '74855', '3');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Peugeot', '3008', '2010', 'black', '1.6 diesel', '198441', '10');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Kia', 'Cerato', '2015', 'gray', '1.6 petrol', '38600', '11');
INSERT INTO `auto_service_db`.`car` (`maker`, `model`, `productionYear`, `color`, `engineType`, `odometer`, `consumer_id`) VALUES ('Hyundai', 'Santa Fe', '2010', 'black', '2.4 petrol', '852149', '13');